### PR TITLE
Python crypt14 support

### PR DESCRIPTION
**Pull request by ElDavoo**
Java support still needs to be written, as is the help text.
The name of the project should also change.
If we want "double support", I guess we need to do more work than this.

### CODE REVIEW

**Comment by beckietech** [comment]
Thank you, I'll give it and try and update result!

**Comment by beckietech** [comment]
After tested both and I also renamed msgstore.db.crypt14 to msgstore.db.crypt12, I got the same error: Key file mismatch or crypt12 file is corrupt. Still dont know why?

**Comment by ElDavoo** [comment]
Which commits did you try?

**Comment by beckietech** [comment]
i tested 0fe0c9a on May23, and fc58433 on May 30. Am I missing something?

**Comment by ElDavoo** [comment]
Hmm no. You can try different values, or you can use a stable version of whatsapp

**Comment by ElDavoo** [comment]
I asked support to detach my fork since nothing of the original code has been left.

**Pull request closed without merging**
